[package]
name = "reference"
version = "0.1.0"
edition = "2018"

# [lib]
# name = "average"
# path = "src/average.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
